# Constants
import os

import arcade

SCREEN_TITLE = "Moon Base Delta"
SCALING = 1.0
MAP_SCALING = 0.25
MODEL_SCALING = 1.0
MOVE_RATE = 5
SPRITE_NATIVE_SIZE = 64
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SCALING)
GRID_PIXEL_SIZE = (SPRITE_SIZE * SCALING)

SCREEN_WIDTH = SPRITE_SIZE * 15
SCREEN_HEIGHT = SPRITE_SIZE * 10

VIEWPORT_MARGIN = 350
AMBIENT_COLOUR = (10, 10, 10)

MUSIC_VOLUME = 0.5

# ***Difficulty***
DIFFICULTY = 1

